DROP TABLE IF EXISTS user_test CASCADE;

DROP TABLE IF EXISTS test_question CASCADE;

DROP TABLE IF EXISTS question_technology CASCADE;

DROP TABLE IF EXISTS profession_chapter CASCADE;

DROP TABLE IF EXISTS chapter_technology CASCADE;

DROP TABLE IF EXISTS question CASCADE;

DROP TABLE IF EXISTS test CASCADE;

DROP TABLE IF EXISTS user CASCADE;

DROP TABLE IF EXISTS technology CASCADE;

DROP TABLE IF EXISTS profession CASCADE;

DROP TABLE IF EXISTS chapter CASCADE;

DROP TYPE IF EXISTS test_status CASCADE;

DROP TYPE IF EXISTS expertise_level CASCADE;