DROP INDEX IF EXISTS users_nickname_unique;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(200),
    ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;
